apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "technical-challenge.fullname" . }}
  namespace: default
rules:
- apiGroups: 
    - ""
    - apps
    - autoscaling
    - batch
    - extensions
    - policy
    - rbac.authorization.k8s.io
  resources:
  - pods
  - deployments
  - services
  - secrets
  - endpoints
  - persistentvolumes
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - get
  - list
  - create