apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "technical-challenge.fullname" . }}
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - ["pods", "deployments", "services", "secrets"]
  verbs:
  - get
  - list
  - create